### ISSUE TITLE
Complete EDHRec Suggestions Feature

### ISSUE THREAD

**Issue by crookedneighbor** [crookedneighbor/shambleshark#1]
- [x] Sync deck (possibly via page refresh) when modal is closed
- [x] Only put edhrec button on commander decks
- [x] Fix issue where multiple button listeners can be added when modal is opened multiple times
- [x] Have edhrec add buttons know if the card is already in the decklist and display a checkmark instead of a plus if that is the case
- [x] Have buttons remove from scryfall deck if the card is already in and the button is clicked
- [x] Support Partner Commanders
- [x] Only put edhrec button on when configured in popup settings
- [x] More intelligently detect when iframe is done loading and can be scrolled into view
- [x] Set up a mutation observer to know when the buttons are ready, rather than using a setTimeout
- [x] Emit a message box on card add error
- [x] Close edhrec modal when backdrop is clicked
- [x] make keyboard accessible
- [x] make screenreader accessible

**Comment by crookedneighbor** [comment]
Outstanding questions:

1) We're using the EDHRec API to get recommendations. This is pretty great, but it sometimes takes a while to load. Is that chance of a long load time worth the wait? Should we go back to scraping the DOM for the card recommendation info from the Commander Page on EDHRec?

1) It opens a modal, which can show about 4 cards at a time. Would it be better to open some sidebar dialog instead? That would allow us to accommodate waaaay more cards. (well, at lease as many cards will fit on the screen)

1) Only a card view is available for selection. Would a card list be a good option to include? Should that block the release?

**Comment by Wihito** [comment]
1. I've tried it a few times now and haven't found the wait to be too long, just a few seconds at most. Scraping could be added as an option or an alternative way to fill the card viewer (both the general page and the personalized recommendations can be interesting to view when brewing)

2. Alternative suggestion, horizontal scrolling card viewer mockup: ![image](https://user-images.githubusercontent.com/9116211/66698530-196dd000-ecdf-11e9-8e12-9eaac6dc6aee.png) This allows viewing of much more cards while not taking up too much space. Just need to figure out a nifty way to scroll sideways.

3. I think card view is better than list with card-on-hover for this feature, it's so much faster with card view and less confusing.

**Comment by crookedneighbor** [comment]
I’m gonna think on the horizontal scrolling option. Generally I dislike horizontal scrolling, unless the app/site’s whole thing is based on that (Trello, for example), but it does solve many of the space issues I was looking to address. So it may be worth it. 

I’ll spike it out and see how it works. I suppose it could always be a preference set in the settings.

**Comment by crookedneighbor** [comment]
Here's an alternative UI:

![alternative](https://user-images.githubusercontent.com/2916945/66976304-166c3a00-f067-11e9-9d0f-daca75de0422.gif)

**Comment by crookedneighbor** [comment]
Went with the drawer UI, because it gives us so much more real estate.
