### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by crookedneighbor** [crookedneighbor/shambleshark#39]

**Comment by Wihito** [comment]
I love typescript, is there a way I can help with this?

**Comment by crookedneighbor** [comment]
Would love help with this. I'm pretty much a noob when it comes to Typescript. Hoping to get an initial PR out tomorrow to get it started. Will ping you on it for review, then we can divvy up the conversion for the rest of it (or you can just see the prs I make and correct me when I do something that's not a best practice :)

**Comment by Wihito** [comment]
I'd like to actively help, that way I get up to speed on the project and I can more easily help with developing stuff after the conversion :)

**Comment by crookedneighbor** [comment]
Got the initial bit out in a PR: https://github.com/crookedneighbor/shambleshark/pull/41

If you have time to look over it, it'd be greatly appreciated!

**Comment by Wihito** [comment]
I'll take a look! I'd put myself at "intermediate" level, worked for a year in a team on an Angular 5 project. No work experience with JavaScript though, more of a beginner on that.

**Comment by crookedneighbor** [comment]
Added a CONTRIBUTING doc https://github.com/crookedneighbor/shambleshark/blob/master/CONTRIBUTING.md

Feel free to make PRs to that as well as you stumble through the project.

**Comment by crookedneighbor** [comment]
I'm going to start converting the tests over to typescript first, because I think that'll make the transition for the actual source code so much easier.

**Comment by Wihito** [comment]
Good idea! I think test driven development is a good approach for this
